#!/bin/bash

set -e

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
DEFAULT=$(tput sgr0)

error_message() {
    printf "\n${RED} ERROR: ${DEFAULT}%s \n\n" "$1"
}

warning_message() {
    printf "\n${YELLOW} WARNING: ${DEFAULT}%s \n\n" "$1"
}

info_message() {
    printf "\n${GREEN} INFO: ${DEFAULT}%s \n\n" "$1"
}

main() {
    local TARGET_BRANCH="$1"

    if [ -z "$TARGET_BRANCH" ]; then
        TARGET_BRANCH=master
        info_message "Assuming the principal branch name with the default value: '${TARGET_BRANCH}'"
    fi

    git checkout -q "$TARGET_BRANCH" && git for-each-ref refs/heads/ "--format=%(refname:short)" | while read -r branch; do mergeBase=$(git merge-base "$TARGET_BRANCH" "$branch") && \
    [[ $(git cherry "$TARGET_BRANCH" $(git commit-tree $(git rev-parse $branch\^{tree}) -p "$mergeBase" -m _)) == "-"* ]] && \
    git branch -D "$branch"; done
}

if [ -z "$1" ]; then
    read -rp "Inform the principal branch name: (master/main) -> " branch
fi

git fetch --all && \
main "$branch"
