#!/bin/bash

set -e

main() {
    local TARGET_BRANCH="$1"
    git checkout -q "$TARGET_BRANCH" && \
    git for-each-ref refs/heads/ "--format=%(refname:short)" | while read -r branch; do mergeBase=$(git merge-base "$TARGET_BRANCH" "$branch") && \
    [[ $(git cherry "$TARGET_BRANCH" $(git commit-tree $(git rev-parse $branch\^{tree}) -p "$mergeBase" -m _)) == "-"* ]] && \
    git branch -D "$branch"; done || true
}

if [ -z "$1" ]; then
    while [ -z "$branch" ]
    do
        read -rp "Inform the principal branch name: (master/main) -> " branch
    done
else
    branch="$1"
fi

git fetch --all && \
main "$branch"
