name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Update OS
        run: sudo apt update
      
      - name: Install git
        run: sudo apt install git -y
      
      - name: Log git version
        run: |
          echo Hello pipeline
          echo $(git --version)
