name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BRANCH_NAME: my-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup
        run: |
          sudo apt update && \
          sudo apt install git -y
      
      - name: Test git-create-branch
        shell: bash
        run: |
          sh ./git-create-branch $BRANCH_NAME
          
          if [[ $? -ne 0 ]]; then
            exit 1
          fi
      
      - name: Test git-log-graph
        shell: bash
        run: |
          sh ./git-log-graph
          
          if [[ $? -ne 0 ]]; then
            exit 1
          fi
        
      - name: Test git-purge-branches
        shell: bash
        run: |
          sh ./git-purge-branches
          
          if [[ $? -ne 0 ]]; then
            exit 1
          fi
          
      - name: Cleanup setup
        if: always()
        run: git push origin --delete $BRANCH_NAME
