name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BRANCH_NAME: my-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Update OS
        run: sudo apt update
      
      - name: Install git
        run: sudo apt install git -y
      
      - name: Test git-create-branch
        shell: bash
        run: |
          sh ./git-create-branch $BRANCH_NAME
          
          if [[ $? -ne 0 ]]
          then
            exit 1
          fi
      
      - name: Test git-log-graph
        shell: bash
        run: |
          sh ./git-log-grah
          
          if [[ $? -ne 0 ]]
          then
            exit 1
          fi
        
      - name: Test git-purge-branchs
        shell: bash
        run: |
          sh ./git-purge-branchs
          
          if [[ $? -ne 0 ]]
          then
            exit 1
          fi
          
      - name: Cleanup
        shell: bash
        run: |
          git push origin --delete $BRANCH_NAME
          
          if [[ $? -ne 0 ]]
          then
            exit 1
          fi
